sudo: required
language: java
addons:
  postgresql: "9.3"
jdk:
  - oraclejdk8
services:
  - postgresql
before_install:
  - sudo bash Vagrant-setup/hadoop_master_new.sh
  - sudo bash Vagrant-setup/travis_create_db_users.sh


