language: java
addons:
  postgresql: "9.3"
jdk:
  - oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'CREATE USER mydrive WITH PASSWORD 'mydrive';' -U postgres
  - psql -c 'create database mydrive;' -U postgres


