sudo: required
language: java
addons:
  postgresql: "9.3"
jdk:
  - oraclejdk8
services:
  - postgresql
before_install:
  - sudo bash Travis-setup/hadoop_master.sh
  - sudo bash Travis-setup/create_db_users.sh


